package com.conamobile.pdfkmp.sampleweb

import com.conamobile.pdfkmp.PdfDocument
import com.conamobile.pdfkmp.markdown.markdown
import com.conamobile.pdfkmp.openInNewTab
import com.conamobile.pdfkmp.pdf
import com.conamobile.pdfkmp.samples.Samples
import com.conamobile.pdfkmp.storage.StorageLocation
import com.conamobile.pdfkmp.storage.save

/**
 * Entry point of the Web (Kotlin/Wasm) sample. Builds a button per sample
 * document; each click generates the PDF in the browser and hands it to the
 * browser's own viewer via [openInNewTab] — PdfKmp ships no web viewer on
 * purpose. When a pop-up blocker eats the tab, the document falls back to a
 * regular download.
 */
fun main() {
    webSamples().forEach { sample ->
        addSampleButton(sample.name, sample.description) {
            val document = sample.make()
            if (document.openInNewTab()) {
                setStatus("Opened “${sample.name}” in a new tab.")
            } else {
                document.save(StorageLocation.Downloads, "${sample.fileName}.pdf")
                setStatus("Pop-up blocked — downloaded ${sample.fileName}.pdf instead.")
            }
        }
    }
    setStatus("Pick a document — it is generated right here in Wasm.")
}

private class WebSample(
    val name: String,
    val fileName: String,
    val description: String,
    val make: () -> PdfDocument,
)

/**
 * The curated subset of [Samples] that needs no image bytes, plus a live
 * `pdfkmp-markdown` demo. Every document is generated by the pure-Kotlin
 * web backend on click.
 */
private fun webSamples(): List<WebSample> = listOf(
    WebSample("Hello world", "hello-world", "The smallest possible document", Samples::helloWorld),
    WebSample("Brochure", "brochure", "Flagship one-pager with gradients", Samples::brochure),
    WebSample("Showcase", "showcase", "Multi-page feature tour", Samples::showcase),
    WebSample("Markdown", "markdown", "pdfkmp-markdown rendering live", ::markdownDemo),
    WebSample("Typography", "typography", "Fonts, weights, letter spacing", Samples::typography),
    WebSample("Advanced text", "text-advanced", "Justify, RTL, hyphenation", Samples::textAdvanced),
    WebSample("Tables", "tables", "Borders, spans, zebra rows", Samples::tableShowcase),
    WebSample("Long table", "long-table", "Page slicing + repeating header", Samples::longTable),
    WebSample("Vector shapes", "vector-shapes", "Paths, gradients, clipping", Samples::vectorShowcase),
    WebSample("Barcodes", "barcodes", "QR, Code 128, EAN-13, Data Matrix", Samples::barcodes),
    WebSample("Design extras", "design-extras", "Charts, shadows, rotation", Samples::designExtras),
    WebSample("Navigation", "navigation", "Bookmarks, links, auto-TOC", Samples::navigation),
    WebSample("Newsletter", "newsletter", "Multi-column magazine flow", Samples::newsletter),
    WebSample("Page templates", "page-templates", "Mixed sizes & orientations", Samples::pageTemplates),
    WebSample("Page chrome", "page-chrome", "Headers, footers, watermark", Samples::pageChrome),
)

/** A live demonstration of the `pdfkmp-markdown` companion on the web backend. */
private fun markdownDemo(): PdfDocument = pdf {
    metadata { title = "Markdown on the Web" }
    page {
        markdown(
            """
            # Markdown → PDF

            This page was written in **Markdown** and rendered by the
            `pdfkmp-markdown` module — *inside your browser*, on Kotlin/Wasm.

            ## What the parser understands

            - Headings, **bold**, *italic*, and `inline code`
            - Ordered and unordered lists
            - Blockquotes and horizontal rules
            - Fenced code blocks
            - Links: [PdfKmp on GitHub](https://github.com/ConaMobileDev/PdfKmp)

            ## A pipe table

            | Module | Purpose |
            | --- | --- |
            | `pdfkmp` | Core DSL + layout + writers |
            | `pdfkmp-markdown` | This very renderer |

            > No JavaScript PDF library was harmed in the making of this
            > document — the bytes come from PdfKmp's pure-Kotlin writer.
            """.trimIndent(),
        )
    }
}

/** Appends a styled sample button to the `#samples` grid in index.html. */
@JsFun(
    """(label, desc, handler) => {
        const btn = document.createElement('button');
        btn.className = 'sample';
        const name = document.createElement('span');
        name.className = 'name';
        name.textContent = label;
        const sub = document.createElement('span');
        sub.className = 'desc';
        sub.textContent = desc;
        btn.appendChild(name);
        btn.appendChild(sub);
        btn.addEventListener('click', handler);
        document.getElementById('samples').appendChild(btn);
    }""",
)
private external fun addSampleButton(label: String, desc: String, handler: () -> Unit)

/** Replaces the `#status` line under the grid. */
@JsFun("(text) => { document.getElementById('status').textContent = text; }")
private external fun setStatus(text: String)
