package com.conamobile.pdfkmp.viewer

import com.conamobile.pdfkmp.PdfDocument

/**
 * Supplies the bytes of an encoded PDF to a [PdfViewer].
 *
 * Today [Bytes] is the only variant — every consumer-facing entry point
 * (a [PdfDocument] generated by `:pdfkmp`, raw bytes loaded from disk or
 * the network, etc.) ultimately reduces to a byte array. Keeping the
 * surface as a sealed interface leaves room to add streaming or
 * platform-handle variants later without breaking the [PdfViewer]
 * signature.
 */
public sealed interface PdfSource {

    /**
     * In-memory PDF bytes as produced by [PdfDocument.toByteArray] or
     * loaded from the filesystem / network by the host app.
     *
     * @property bytes raw `%PDF-…` bytes. The viewer keeps a reference
     *   for the lifetime of the composition; do not mutate the array
     *   after passing it in.
     */
    public class Bytes(public val bytes: ByteArray) : PdfSource

    public companion object {

        /** Convenience factory for an in-memory [PdfDocument]. */
        public fun of(document: PdfDocument): PdfSource = Bytes(document.toByteArray())

        /** Convenience factory for raw bytes — same as `Bytes(bytes)`. */
        public fun of(bytes: ByteArray): PdfSource = Bytes(bytes)
    }
}

/** Returns the underlying byte array regardless of the variant. */
internal fun PdfSource.bytes(): ByteArray = when (this) {
    is PdfSource.Bytes -> bytes
}
String> = emptyMap(),
    ) : PdfSource

    public companion object {

        /** Convenience factory for an in-memory [PdfDocument]. */
        public fun of(document: PdfDocument): PdfSource = Bytes(document.toByteArray())

        /** Convenience factory for raw bytes — same as `Bytes(bytes)`. */
        public fun of(bytes: ByteArray): PdfSource = Bytes(bytes)

        /** Convenience factory for a remote URL. */
        public fun of(url: String, headers: Map<String, String> = emptyMap()): PdfSource =
            Url(url, headers)
    }
}
